Repository vince-fugnitto/local-history-ext, pull requests merged in 2020-06, with the labels that each got.

#116 tree-view: update user-interface
  package.json
  src/extension.ts
  src/local-history/local-history-tree-provider.ts
Labels: enhancement

#128 [bug] View History command doesn't work
  src/local-history/local-history-manager.ts
Labels: critical, theia

#130 electron: fix local-history creation
  package-lock.json
  package.json
  src/local-history/local-history-manager.ts
  src/local-history/local-history.d.ts
Labels: bug, critical, theia

#131 icon: fix display of icons
  package.json
  resources/dark/history.svg
  resources/dark/refresh.svg
  resources/dark/trash.svg
  resources/light/history.svg
  resources/light/refresh.svg
  resources/light/trash.svg
Labels: bug, theia

#144 fix 'find-remove' dependency
  package-lock.json
  package.json
Labels: critical

#149 Add info about revision context metadata
  README.md
Labels: documentation
